export default {
  USER_NOT_FOUND: 'User not found',
  WRONG_PASS: 'Wrong password entered',
  EMAIL_USED: 'User with this email is already registered',
  NOT_AUTHORIZED: 'User is not authorized',
  INCORRECT_DATA: 'incorrect data entered',
  SERVER_ERROR: 'Internal Server Error',
  INVALID_TOKEN: 'Invalid token',
  NOT_REGISTRED: 'User not registered',
  BOOK_NOT_FOUND: 'Book not found',
  BOOKS_NOT_FOUND: 'Books not found',
  BOOK_NOT_FOUND_IN_FAVORITES: 'Book not found in favorites',
  CART_IS_EMPTY: 'Cart is empty',
  NOT_FOUND_ITEM_IN_CART: 'Not found item in cart',
};
