export const USER_NOT_FOUND = 'User not found';
export const WRONG_PASS = 'Wrong password entered';
export const EMAIL_USED = 'User with this email is already registered';
export const NOT_AUTHORIZED = 'User is not authorized';
export const INCORRECT_DATA = 'incorrect data entered';
export const SERVER_ERROR = 'Internal Server Error';
export const INVALID_TOKEN = 'Invalid token';
export const NOT_REGISTRED = 'User not registered';
export const BOOK_NOT_FOUND = 'Book not found';
